version: '3.8'
services:
  pumubot-db:
    container_name: pumubot-db
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
volumes:
  mongo-data:
