version: '3.8'

name: pumubot
services:
  pumubot-db:
    container_name: pumubot-db
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
  pumubot-bot:
    container_name: pumubot-bot
    image: pumubot
    env_file:
      - ../.env
volumes:
  mongo-data: