name: Pumubot CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches:
      - "main"
      - "releases/*"

env:
  my_token: ${{secrets.GITHUB_TOKEN}}

jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build and Test (NodeJS)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
