name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment configured to deploy
        default: 'mitadoble'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Build docker image'
      uses: ./build-docker-image.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Connect and pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }};
          docker compose pull && docker compose up -d"