name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment configured to deploy
        default: 'mitadoble'

jobs:
  build:
    name: 'Build docker image'
    uses: ./.github/workflows/build-docker-image.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Checkout code to copy docker compose
        uses: actions/checkout@v4

      - name: Copy prod.docker-compose.yml to remote server
        run: scp ./docker-compose/prod.docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/docker-compose.yml

      - name: Connect and pull
        run: |
          
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }};
          docker compose pull && 

          DISCORD_TOKEN='${{secrets.DISCORD_TOKEN}}' DISCORD_CLIENT_ID='${{vars.DISCORD_CLIENT_ID}}' MOCK_CONFIG='${{vars.MOCK_CONFIG}}' DEV_SERVER_ID='${{vars.DEV_SERVER_ID}}' MONGO_DB_URI='${{secrets.MONGO_DB_URI}}' docker compose up -d"